### ISSUE TITLE
=> throws an error

### ISSUE THREAD

**Issue by Eeems** [IJzerbaard/haroldbot#1] opened 2016-09-06 17:16 UTC
http://haroldbot.nl/?q=-2+%3D%3E+9000
Turns out if you attempt to (incorrectly) compare via greater then or equals via the following command `=>` the site will return `Severe bug in Binary.toBddFunc`
You will also get the following error on the console `TypeError: (intermediate value).AnalyzeTruth is undefined`

**Comment by IJzerbaard** [comment] 2016-09-06 17:33
Fixed with 62aff2f5cbe31f501949f766c4cbb734bdcc54b4 , so now `=>` is the implication operator as it was intended to be (it was parsed but never turned into a BDD).

**Closed as completed by IJzerbaard** 2016-09-06 17:33 UTC
Labels: bug
